-- 修正拼写：BOLB → BLOB
CREATE TABLE IF NOT EXISTS CC_CAS_BLOB (
	sha512 BYTEA NOT NULL,
	name TEXT NOT NULL,
	mime TEXT NOT NULL,
	data BYTEA NOT NULL,
	size INTEGER NOT NULL
);

-- 为 SHA-512 建索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_cc_cas_blob_sha512 ON CC_CAS_BLOB (sha512);
